name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --all-targets --verbose
    - name: ls
      run: ls target/debug
    - name: Run tests
      run: cargo test --features test --all --all-targets --verbose
  Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --all-targets --verbose
    - name: Run tests
      run: cargo test --features test --all --all-targets --verbose