name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Redis server
      run: docker build . -t ris -f ./dockerfile && docker run -p 6379:6379 -d ris && docker ps -a
    - name: Run tests
      run: cargo test integration
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Redis server
      run: docker build . -t ris -f ./dockerfile && docker run -p 6379:6379 -d ris && docker ps -a
    - name: Run tests
      run: cargo test integration