name: DeployBot
on:
  push: 
    branches: [master]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploying version
      uses: danitseitlin/package-deployer@master
      with:
        pkg_name: redis-interval-sets
        main_pkg_manager: github
        pkg_managers: '[github]'
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.G_AUTH_TOKEN}}
